export default {
    ERROR: -1,
    START: 0,
    HELP: 1,
    ECHO: 2,
    TOKEN: 3,

    FLIGHT_SEARCH_START: 4,
    FLIGHT_SEARCH_SHOW_LIST_BY_INPUT: 7,

    FLIGHT_SEARCH_SELECT: 8,
    FLIGHT_SUBSCRIBE: 9,
    FLIGHT_UNSUBSCRIBE: 10,

    USER_FLIGHTS: 11
}
